### ISSUE TITLE
Change to 4.5 the .net version

### ISSUE THREAD

**Issue by regisbsb** [papci/BasicHttpAuth#2]
.NET framework 4.5.2 is unnecessary and prohibitive for some projects. Some one at 4.5.2 that installs a 4.5 will be benefiting of the latest features anyway but the module itself does not use anything that needs 4.5.2. The oposite is not true. Someone at 4.5 cannot use a 4.5.2 nuget package.

**Comment by regisbsb** [comment]
May I ask you, @papci to publish a new nuget package please?

**Comment by pehadavid** [comment]
Hi,

The new version is now available on nuget.org. Thanks for your patience.

**Comment by regisbsb** [comment]
No worries at all
